import fs from 'fs';

const FIXES = {
  "たこ焼き": { lat: 34.6937, lng: 135.5023 }, // Osaka
  "寿司": { lat: 35.6895, lng: 139.6917 }, // Tokyo
  "団子": { lat: 35.0116, lng: 135.7681 }, // Kyoto
  "お好み焼き": { lat: 34.3853, lng: 132.4553 }, // Hiroshima
  "もんじゃ": { lat: 35.6636, lng: 139.7820 }, // Tsukishima, Tokyo
  "きょんぼっくん": { lat: 37.5796, lng: 126.9770 }, // Seoul (Gyeongbokgung)
  "水原": { lat: 37.2636, lng: 127.0286 }, // Suwon, KR
  "北村韓屋": { lat: 37.5826, lng: 126.9836 }, // Bukchon, KR
  "台北　九分　": { lat: 25.1095, lng: 121.8444 }, // Jiufen, TW
  "台南　ランタン": { lat: 23.0036, lng: 120.2144 }, // Tainan, TW
  "香港　寺": { lat: 22.3193, lng: 114.1694 }, // HK
  "インド　ガンジス川": { lat: 25.3176, lng: 82.9739 }, // Varanasi, IN
  "仏教ロータス祭り": { lat: 37.5665, lng: 126.9780 }, // Seoul, KR
  "韓国": { lat: 37.5665, lng: 126.9780 },
  "台湾": { lat: 25.0330, lng: 121.5654 },
  "秦野七福神": { lat: 35.3725, lng: 139.2195 },
  "東京タワー　鯉のぼり": { lat: 35.6586, lng: 139.7454 },
  "出雲": { lat: 35.3614, lng: 132.7562 },
  "大久野島": { lat: 34.3093, lng: 132.9930 },
  "岩手さんさ": { lat: 39.7020, lng: 141.1545 },
  "長崎ランタン": { lat: 32.7503, lng: 129.8777 },
  "弘前　桜まつり": { lat: 40.6053, lng: 140.4635 },
  "青森ねぶた": { lat: 40.8246, lng: 140.7397 },
  "ねぶた": { lat: 40.8246, lng: 140.7397 },
  "仙台七夕": { lat: 38.2682, lng: 140.8694 },
  "竿燈祭り": { lat: 39.7186, lng: 140.1023 },
  "万等祭り": { lat: 35.0000, lng: 137.0000 },
  "関ヶ原": { lat: 35.3622, lng: 136.4608 }
};

// Also apply some variance to identical coordinates so they don't exactly overlap
const variance = () => (Math.random() - 0.5) * 0.05;

async function main() {
  const filePath = './src/parsedLocations.js';
  let content = fs.readFileSync(filePath, 'utf8');
  
  // Extract the array logic
  content = content.replace('// THIS FILE IS AUTO-GENERATED BY scripts/geocode.js\nexport const locations = ', '');
  content = content.replace(/;\n$/, '');
  
  let data;
  try {
    data = JSON.parse(content);
  } catch (e) {
    console.error("Failed to parse parsedLocations.js as JSON", e);
    return;
  }
  
  let fixedCount = 0;
  data.forEach(loc => {
    // Check exact matches or includes
    for (const [key, coords] of Object.entries(FIXES)) {
      if (loc.name.includes(key) || loc.name === key) {
        loc.lat = coords.lat + variance();
        loc.lng = coords.lng + variance();
        fixedCount++;
        break; // Only apply first match
      }
    }
  });

  const outputCode = '// THIS FILE IS AUTO-GENERATED BY scripts/geocode.js\nexport const locations = ' + JSON.stringify(data, null, 2) + ';\n';
  fs.writeFileSync(filePath, outputCode, 'utf8');
  console.log("Successfully fixed " + fixedCount + " coordinate entries in src/parsedLocations.js");
}

main().catch(console.error);
