import fs from 'fs';
import { parse } from 'csv-parse/sync';
import https from 'https';

// A simple delay function to avoid rate limits on Nominatim
const delay = ms => new Promise(res => setTimeout(res, ms));

async function fetchCoordinates(query) {
  return new Promise((resolve, reject) => {
    // Adding ' Japan' to improve search accuracy
    const url = `https://nominatim.openstreetmap.org/search?q=${encodeURIComponent(query + ' 日本')}&format=json&limit=1`;
    const options = {
      headers: {
        'User-Agent': 'ReactThreeFiberApp/1.0 (JapanMapDemo)'
      }
    };
    https.get(url, options, (res) => {
      let data = '';
      res.on('data', chunk => { data += chunk; });
      res.on('end', () => {
        try {
          const result = JSON.parse(data);
          if (result && result.length > 0) {
            resolve({ lat: parseFloat(result[0].lat), lng: parseFloat(result[0].lon) });
          } else {
            resolve(null);
          }
        } catch (e) {
          resolve(null);
        }
      });
    }).on('error', (err) => resolve(null));
  });
}

// Convert "21/4/19" or "2020/11/27" into timestamp
function parseDate(dateStr) {
  if (!dateStr) return 0;
  const parts = dateStr.split('/');
  if (parts.length === 3) {
    let year = parseInt(parts[0], 10);
    if (year < 100) year += 2000;
    const month = parseInt(parts[1], 10) - 1;
    const day = parseInt(parts[2], 10);
    return new Date(year, month, day).getTime();
  }
  return 0;
}

// Extract Video ID from URL like "https://youtu.be/SdEsUKnyZi4"
function extractVideoId(url) {
  if (!url) return '';
  const match = url.match(/youtu\.be\/([^?&]+)/) || url.match(/youtube\.com\/watch\?v=([^?&]+)/);
  return match ? match[1] : '';
}

async function main() {
  console.log('Reading CSV...');
  const fileContent = fs.readFileSync('youtube list.csv', 'utf8');
  
  const records = parse(fileContent, {
    columns: false,
    skip_empty_lines: true
  });

  const categoriesMap = ['雪', '祭', '緑', '田舎', '都市', '水', '火', '伝統', '動物', '夜', '神社', '寺', '島', '城', '温泉', '食'];
  
  const parsedData = [];
  let idCounter = 1;

  console.log(`Found ${records.length - 1} records. Starting geocoding...`);

  // Random fallback coordinates in Japan bounding box roughly (Honshu mostly)
  const getRandomCoordinate = () => {
    const lat = 34 + Math.random() * 4;
    const lng = 135 + Math.random() * 5;
    return { lat, lng };
  };

  // Skip header row
  for (let i = 1; i < records.length; i++) {
    const row = records[i];
    const name = row[0];
    const url = row[1];
    const dateStr = row[2];
    
    if (!name || !url) continue;

    console.log(`[${i}/${records.length - 1}] Fetching coordinates for: ${name}`);
    let coords = await fetchCoordinates(name);
    
    // Retry once with a lighter query if it fails (e.g. remove spaces or '祭り')
    if (!coords) {
      const simplifiedQuery = name.replace('祭り', '').replace('祭', '').trim();
      if (simplifiedQuery !== name) {
         await delay(1000); // 1 sec delay per Nominatim policy
         coords = await fetchCoordinates(simplifiedQuery);
      }
    }

    if (!coords) {
      console.log(`   -> Warning: Could not find ${name}, using random fallback.`);
      coords = getRandomCoordinate();
    } else {
      console.log(`   -> Found: ${coords.lat}, ${coords.lng}`);
    }

    const categoriesList = [];
    for (let c = 0; c < categoriesMap.length; c++) {
      if (row[c + 3] && row[c + 3].includes('⚪︎')) { // offset is 3: name, url, date... wait ! row structure is [name, url, date, cat1, cat2...] -> index 3 is first category.
        categoriesList.push(categoriesMap[c]);
      }
    }

    const videoId = extractVideoId(url);
    const dateValue = parseDate(dateStr);

    parsedData.push({
      id: idCounter++,
      name,
      videoId,
      videoUrl: `https://www.youtube.com/embed/${videoId}`, 
      rawUrl: url,
      dateTitle: dateStr || '不明',
      dateValue,
      categories: categoriesList,
      // For UI styling, we pick a primary genre from some common map keywords
      genre: categoriesList.includes('祭') ? 'matsuri' : 
             categoriesList.includes('緑') ? 'nature' : 
             categoriesList.includes('都市') ? 'city' : 
             categoriesList.includes('雪') ? 'winter' : 'nature',
      desc: categoriesList.join(', ') || 'カテゴリなし',
      lat: coords.lat,
      lng: coords.lng
    });

    await delay(1100); // Respect Nominatim's 1 req/sec policy
  }

  const outputCode = `// THIS FILE IS AUTO-GENERATED BY scripts/geocode.js\nexport const locations = ${JSON.stringify(parsedData, null, 2)};\n`;
  fs.writeFileSync('./src/parsedLocations.js', outputCode, 'utf8');
  console.log('Successfully wrote src/parsedLocations.js');
}

main().catch(console.error);
